version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - app_logs:/app/logs
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay

volumes:
  db_data:
  app_logs:
